name: Deploy PWA Template to GitHub Pages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build PWA
        run: |
          # Clean docs directory
          rm -rf docs/*
          
          # Copy source files to docs
          cp -r src/* docs/
          
          # Generate build info
          echo "Build completed at $(date)" > docs/build-info.txt
          echo "Commit: ${{ github.sha }}" >> docs/build-info.txt
          echo "Branch: ${{ github.ref_name }}" >> docs/build-info.txt
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: # Add custom domain here if needed
